# Generated by Django 5.2.7 on 2025-11-01 07:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_appointment_notes_pet_weight_vaccinerecord_remarks_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vetavailability',
            options={'ordering': ['date', 'start_time'], 'verbose_name': 'Vet Availability', 'verbose_name_plural': 'Vet Availabilities'},
        ),
        migrations.RemoveField(
            model_name='pet',
            name='weight',
        ),
        migrations.AddField(
            model_name='pet',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='pet_images/'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='age',
            field=models.PositiveIntegerField(default=0, help_text='Age in months'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pet',
            name='breed',
            field=models.CharField(blank=True, default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vetavailability',
            name='doctor',
            field=models.ForeignKey(limit_choices_to={'is_staff': True}, on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to=settings.AUTH_USER_MODEL),
        ),
    ]
