# Generated by Django 5.2.7 on 2026-05-10 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_payment_verified_at_alter_payment_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GcashQR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='gcash/')),
                ('instructions', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
