# Generated by Django 5.2.7 on 2026-05-10 18:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_clinicsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='vetavailability',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vetavailability',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
