# Generated by Django 5.2.7 on 2025-11-02 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_pet_birthday_pet_color_vaccinerecord_weight_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
