# Generated by Django 5.2.7 on 2025-11-02 11:38

from django.db import migrations, models  # ✅ Make sure models is imported

class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_pet_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='contact',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='owner',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='owner',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
