# Generated by Django 5.2.7 on 2025-11-22 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_workingday'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workingday',
            old_name='is_active',
            new_name='afternoon_open',
        ),
        migrations.AddField(
            model_name='workingday',
            name='morning_open',
            field=models.BooleanField(default=True),
        ),
    ]
