# Generated by Django 5.2.7 on 2026-05-12 22:36

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_payment_screenshot'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VaccinationReminderLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_to', models.EmailField(max_length=254)),
                ('sent_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('subject', models.CharField(max_length=255)),
                ('sent_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_vaccination_reminders', to=settings.AUTH_USER_MODEL)),
                ('vaccine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminder_logs', to='main.vaccine')),
            ],
            options={
                'ordering': ['-sent_at'],
            },
        ),
    ]
