# Generated by Django 5.2.7 on 2025-11-22 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_rename_is_active_workingday_afternoon_open_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workingday',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
