# Generated by Django 5.2.7 on 2025-11-27 11:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_pet_is_active_history'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vaccine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_given', models.DateField()),
                ('next_due', models.DateField(blank=True, null=True)),
                ('weight', models.FloatField()),
                ('vaccine_name', models.CharField(max_length=255)),
                ('manufacturer', models.CharField(blank=True, max_length=255)),
                ('veterinarian', models.CharField(blank=True, max_length=255)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.pet')),
            ],
        ),
        migrations.CreateModel(
            name='VaccineRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vaccine_name', models.CharField(max_length=100)),
                ('manufacturer', models.CharField(max_length=100)),
                ('date_given', models.DateField()),
                ('next_due', models.DateField()),
                ('veterinarian', models.CharField(max_length=100)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.pet')),
            ],
        ),
    ]
