# Generated by Django 5.2.7 on 2025-11-27 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_vaccine_vaccinerecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaccine',
            name='weight',
            field=models.DecimalField(decimal_places=1, max_digits=5),
        ),
    ]
