# Generated by Django 5.2.7 on 2025-11-27 13:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_vaccine_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaccine',
            name='manufacturer',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='vaccine',
            name='pet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vaccine_records', to='main.pet'),
        ),
        migrations.AlterField(
            model_name='vaccine',
            name='vaccine_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='vaccine',
            name='veterinarian',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='vaccine',
            name='weight',
            field=models.FloatField(),
        ),
    ]
