# Generated by Django 5.2.7 on 2025-11-28 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_vaccine_manufacturer_alter_vaccine_pet_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='history',
            name='diagnosis',
        ),
        migrations.RemoveField(
            model_name='history',
            name='treatment',
        ),
        migrations.AlterField(
            model_name='history',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
