# Generated by Django 5.2.7 on 2025-11-28 04:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_remove_history_diagnosis_remove_history_treatment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='pet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.pet'),
        ),
        migrations.AlterField(
            model_name='history',
            name='pet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.pet'),
        ),
        migrations.AlterField(
            model_name='vaccination',
            name='pet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vaccinations', to='main.pet'),
        ),
        migrations.AlterField(
            model_name='vaccine',
            name='pet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vaccine_records', to='main.pet'),
        ),
        migrations.AlterField(
            model_name='vaccinerecord',
            name='pet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.pet'),
        ),
    ]
