# Generated by Django 5.2.7 on 2025-11-28 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_alter_appointment_pet_alter_history_pet_and_more'),
    ]

    operations = [
    ]
